import express from 'express';
import { getAdminDashboard, listAdminAppointments } from '../controllers/adminDashboardController.js';
import { getAdminAppointmentOptions, createAdminAppointment, getAdminAppointment, updateAdminAppointment, convertAdminAppointmentToJob } from '../controllers/adminAppointmentController.js';
import { listAdminCustomers, getAdminCustomer, createAdminCustomer, updateAdminCustomer } from '../controllers/adminCustomerController.js';
import { listAdminVehicles, getAdminVehicle, createAdminVehicle, updateAdminVehicle } from '../controllers/adminVehicleController.js';
import { listAdminServiceTypes, createAdminServiceType, updateAdminServiceType, deactivateAdminServiceType } from '../controllers/adminServiceTypeController.js';
import { listAdminTechnicians, createAdminTechnician, getAdminTechnician, updateAdminTechnician, updateAdminTechnicianAvailability } from '../controllers/adminTechnicianController.js';
import { listAdminAllocations, updateAdminJobTechnician } from '../controllers/adminAllocationController.js';
import { listAdminJobBoard } from '../controllers/adminJobBoardController.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

const router = express.Router();
router.use(requireAuth, requireRole('Admin'));
router.get('/dashboard', getAdminDashboard);
router.get('/appointments', listAdminAppointments);
router.get('/appointment-options', getAdminAppointmentOptions);
router.post('/appointments', createAdminAppointment);
router.get('/appointments/:appointmentId', getAdminAppointment);
router.patch('/appointments/:appointmentId', updateAdminAppointment);
router.post('/appointments/:appointmentId/convert-to-job', convertAdminAppointmentToJob);
router.get('/customers', listAdminCustomers);
router.post('/customers', createAdminCustomer);
router.get('/customers/:customerId', getAdminCustomer);
router.patch('/customers/:customerId', updateAdminCustomer);
router.get('/vehicles', listAdminVehicles);
router.post('/vehicles', createAdminVehicle);
router.get('/vehicles/:vehicleId', getAdminVehicle);
router.patch('/vehicles/:vehicleId', updateAdminVehicle);
router.get('/service-types', listAdminServiceTypes);
router.post('/service-types', createAdminServiceType);
router.patch('/service-types/:serviceTypeId', updateAdminServiceType);
router.delete('/service-types/:serviceTypeId', deactivateAdminServiceType);
router.get('/technicians', listAdminTechnicians);
router.post('/technicians', createAdminTechnician);
router.get('/technicians/:technicianId', getAdminTechnician);
router.patch('/technicians/:technicianId', updateAdminTechnician);
router.patch('/technicians/:technicianId/availability', updateAdminTechnicianAvailability);
router.get('/allocations', listAdminAllocations);
router.get('/jobs', listAdminJobBoard);
router.patch('/jobs/:jobId/technician', updateAdminJobTechnician);

export default router;
