import express from 'express';
import { listAdminUsers, updateAdminUserRole } from '../controllers/adminUserController.js';
import { getAdminDashboard, listAdminAppointments } from '../controllers/adminDashboardController.js';
import { getAdminAppointmentOptions, createAdminAppointment, getAdminAppointment, updateAdminAppointment, convertAdminAppointmentToJob } from '../controllers/adminAppointmentController.js';
import { listAdminCustomers, getAdminCustomer, createAdminCustomer, updateAdminCustomer, setAdminCustomerStatus } from '../controllers/adminCustomerController.js';
import { listAdminVehicles, getAdminVehicle, createAdminVehicle, updateAdminVehicle } from '../controllers/adminVehicleController.js';
import { listAdminServiceTypes, createAdminServiceType, updateAdminServiceType, deactivateAdminServiceType, deleteAdminServiceType } from '../controllers/adminServiceTypeController.js';
import { listAdminTechnicians, createAdminTechnician, getAdminTechnician, updateAdminTechnician, updateAdminTechnicianAvailability } from '../controllers/adminTechnicianController.js';
import { listAdminAllocations, updateAdminJobTechnician } from '../controllers/adminAllocationController.js';
import { listAdminJobBoard } from '../controllers/adminJobBoardController.js';
import { createAdminAccount, resetAdminAccountPassword } from '../controllers/adminAccountController.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

const router = express.Router();
router.use(requireAuth, requireRole('Admin'));
router.get('/users', listAdminUsers);
router.patch('/users/:userId/role', updateAdminUserRole);
router.get('/dashboard', getAdminDashboard);
router.get('/appointments', listAdminAppointments);
router.get('/appointment-options', getAdminAppointmentOptions);
router.post('/appointments', createAdminAppointment);
router.get('/appointments/:appointmentId', getAdminAppointment);
router.patch('/appointments/:appointmentId', updateAdminAppointment);
router.post('/appointments/:appointmentId/convert-to-job', convertAdminAppointmentToJob);
router.get('/customers', listAdminCustomers);
router.post('/customers', createAdminCustomer);
router.get('/customers/:customerId', getAdminCustomer);
router.patch('/customers/:customerId/status', setAdminCustomerStatus);
router.patch('/customers/:customerId', updateAdminCustomer);
router.get('/vehicles', listAdminVehicles);
router.post('/vehicles', createAdminVehicle);
router.get('/vehicles/:vehicleId', getAdminVehicle);
router.patch('/vehicles/:vehicleId', updateAdminVehicle);
router.get('/service-types', listAdminServiceTypes);
router.post('/service-types', createAdminServiceType);
router.patch('/service-types/:serviceTypeId', updateAdminServiceType);
router.patch('/service-types/:serviceTypeId/deactivate', deactivateAdminServiceType);
router.delete('/service-types/:serviceTypeId', deleteAdminServiceType);
router.get('/technicians', listAdminTechnicians);
router.post('/technicians', createAdminTechnician);
router.get('/technicians/:technicianId', getAdminTechnician);
router.patch('/technicians/:technicianId', updateAdminTechnician);
router.patch('/technicians/:technicianId/availability', updateAdminTechnicianAvailability);
router.get('/allocations', listAdminAllocations);
router.get('/jobs', listAdminJobBoard);
router.patch('/jobs/:jobId/technician', updateAdminJobTechnician);
router.post('/accounts', createAdminAccount);
router.patch('/accounts/:accountId/password', resetAdminAccountPassword);

export default router;
