import { test } from 'node:test';
import assert from 'node:assert/strict';
import bcrypt from 'bcrypt';
import { createApp } from '../app.js';
import User from '../models/User.js';
import AuthSession from '../models/AuthSession.js';
import ServiceJob from '../models/ServiceJob.js';
import Notification from '../models/Notification.js';
import JobPhoto from '../models/JobPhoto.js';
import Invoice from '../models/Invoice.js';
import Vehicle from '../models/Vehicle.js';
import Appointment from '../models/Appointment.js';
import Payment from '../models/Payment.js';
import { invoiceEmail } from '../services/invoiceEmail.js';
import { passwordResetEmail } from '../services/passwordResetEmail.js';
import { hashToken } from '../utils/session.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

test('auth HTTP flow: credentials, cookies, access, logout and one-time password reset', async t => {
  const customer = { _id: 'customer', name: 'Test Customer', email: 'customer@example.com', mobile: '+94771234567', password: await bcrypt.hash('old-password', 10), role: 'user', isActive: true, sessionVersion: 0, async save() { return this; } };
  const billingAdmin = { _id: 'finance-user', name: 'Finance User', email: 'finance@example.com', password: await bcrypt.hash('finance-password', 10), role: 'Admin', isActive: true, sessionVersion: 0 };
  const users = [customer, billingAdmin];
  let reportTechnician = null;
  const sessions = [];
  let sentEmail;
  t.mock.method(User, 'findOne', async query => users.find(user => (!query.email || user.email === query.email) && (!query.mobile || user.mobile === query.mobile) && (!query.isActive || user.isActive !== false)) || null);
  t.mock.method(User, 'findById', id => ({ select: async () => users.find(user => user._id === id) || null }));
  t.mock.method(User, 'find', query => ({ select() { return this; }, sort() { return this; }, lean: async () => query?.role === 'Technician' ? [reportTechnician] : [{ _id: 'admin-user' }] }));
  t.mock.method(User, 'updateOne', async (query, update) => {
    const user = users.find(user => user._id === query._id && (!query.resetTokenHash || user.resetTokenHash === query.resetTokenHash));
    if (user) {
      Object.assign(user, update.$set || {});
      for (const key of Object.keys(update.$unset || {})) delete user[key];
    }
    return { modifiedCount: user ? 1 : 0 };
  });
  t.mock.method(User, 'findOneAndUpdate', async (query, update) => {
    const user = users.find(user => user.resetTokenHash === query.resetTokenHash && user.resetTokenExpiresAt > query.resetTokenExpiresAt.$gt && user.isActive !== false);
    if (!user) return null;
    Object.assign(user, update.$set);
    user.sessionVersion += update.$inc.sessionVersion;
    for (const key of Object.keys(update.$unset)) delete user[key];
    return user;
  });
  t.mock.method(AuthSession, 'create', async data => { sessions.push(data); return data; });
  t.mock.method(AuthSession, 'findOne', async query => sessions.find(session => session.tokenHash === query.tokenHash && session.expiresAt > query.expiresAt.$gt) || null);
  t.mock.method(AuthSession, 'deleteOne', async query => {
    const index = sessions.findIndex(session => session.tokenHash === query.tokenHash);
    if (index !== -1) sessions.splice(index, 1);
  });
  t.mock.method(AuthSession, 'deleteMany', async query => {
    const remaining = sessions.filter(session => session.user !== query.user);
    const deletedCount = sessions.length - remaining.length;
    sessions.splice(0, sessions.length, ...remaining);
    return { deletedCount };
  });
  t.mock.method(passwordResetEmail, 'isConfigured', () => true);
  t.mock.method(passwordResetEmail, 'send', async (email, token) => { sentEmail = { email, token }; });
  const app = createApp();
  app.get('/test/admin', requireAuth, requireRole('Admin'), (req, res) => res.json({ ok: true }));
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const url = `http://127.0.0.1:${server.address().port}`;
  async function request(path, { body, cookie, origin, method } = {}) {
    const response = await fetch(url + path, {
      method: method || (body === undefined ? 'GET' : 'POST'),
      headers: { ...(body === undefined ? {} : { 'Content-Type': 'application/json' }), ...(cookie ? { Cookie: cookie } : {}), ...(origin ? { Origin: origin } : {}) },
      ...(body === undefined ? {} : { body: JSON.stringify(body) }),
    });
    return { response, data: await response.json(), cookie: response.headers.get('set-cookie')?.split(';')[0] };
  }
  try {
    assert.equal((await request('/api/auth/me')).response.status, 401);
    assert.equal((await request('/api/auth/me', { method: 'PATCH', body: { fullName: 'Changed', email: 'changed@example.com', mobile: '' } })).response.status, 401);
    assert.equal((await request('/api/auth/login', { body: { email: {} } })).response.status, 400);
    assert.equal((await request('/api/auth/login', { body: { email: customer.email, password: 'wrong' } })).response.status, 401);
    assert.equal((await request('/api/auth/login', { origin: 'https://other.example', body: { email: customer.email, password: 'old-password' } })).response.status, 403);
    const login = await request('/api/auth/login', { origin: 'http://localhost:5173', body: { email: ' CUSTOMER@example.com ', password: 'old-password', remember: true } });
    assert.equal(login.response.status, 200);
    assert.equal(login.data.role, 'Customer');
    assert.equal(login.data.password, undefined);
    assert.equal(login.data.token, undefined);
    assert.match(login.response.headers.get('set-cookie'), /HttpOnly/);
    assert.match(login.response.headers.get('set-cookie'), /SameSite=Lax/);
    assert.match(login.response.headers.get('set-cookie'), /Max-Age=2592000/);
    assert.equal(login.response.headers.get('access-control-allow-credentials'), 'true');
    assert.equal(login.response.headers.get('cache-control'), 'no-store');
    assert.equal(sessions[0].tokenHash, hashToken(login.cookie.split('=')[1]));
    assert.equal((await request('/api/auth/me', { cookie: login.cookie })).data.fullName, customer.name);
    assert.equal((await request('/test/admin', { cookie: login.cookie })).response.status, 403);

    customer.isActive = false;
    assert.equal((await request('/api/auth/me', { cookie: login.cookie })).response.status, 401);
    assert.equal((await request('/api/auth/login', { body: { email: customer.email, password: 'old-password' } })).response.status, 401);
    customer.isActive = true;
    sessions[0].expiresAt = new Date(Date.now() - 1000);
    assert.equal((await request('/api/auth/me', { cookie: login.cookie })).response.status, 401);
    sessions[0].expiresAt = new Date(Date.now() + 60000);
    const logout = await request('/api/auth/logout', { cookie: login.cookie, body: {} });
    assert.equal(logout.response.status, 200);
    assert.match(logout.response.headers.get('set-cookie'), /Expires=Thu, 01 Jan 1970/);
    assert.equal((await request('/api/auth/me', { cookie: login.cookie })).response.status, 401);
    assert.equal((await request('/api/auth/logout', { body: {} })).response.status, 200);

    const mobileLogin = await request('/api/auth/login', { body: { email: '+94 (77) 123-4567', password: 'old-password' } });
    assert.equal(mobileLogin.response.status, 200);
    assert.doesNotMatch(mobileLogin.response.headers.get('set-cookie'), /Max-Age/);
    const known = await request('/api/auth/forgot-password', { body: { email: ' CUSTOMER@example.com ' } });
    const unknown = await request('/api/auth/forgot-password', { body: { email: 'unknown@example.com' } });
    assert.deepEqual(known.data, unknown.data);
    assert.equal(sentEmail.email, customer.email);
    assert.equal(customer.resetTokenHash, hashToken(sentEmail.token));
    assert.notEqual(customer.resetTokenHash, sentEmail.token);
    assert.ok(customer.resetTokenExpiresAt > new Date());
    assert.equal(known.data.token, undefined);
    assert.equal((await request('/api/auth/reset-password', { body: { token: sentEmail.token, password: 'new-password', confirmPassword: 'different' } })).response.status, 400);
    customer.resetTokenExpiresAt = new Date(Date.now() - 1000);
    assert.equal((await request('/api/auth/reset-password', { body: { token: sentEmail.token, password: 'new-password', confirmPassword: 'new-password' } })).response.status, 400);
    customer.resetTokenExpiresAt = new Date(Date.now() + 60000);
    const resetBody = { token: sentEmail.token, password: 'new-password', confirmPassword: 'new-password' };
    assert.equal((await request('/api/auth/reset-password', { body: resetBody })).response.status, 200);
    assert.equal(await bcrypt.compare('new-password', customer.password), true);
    assert.equal((await request('/api/auth/reset-password', { body: resetBody })).response.status, 400);
    assert.equal((await request('/api/auth/me', { cookie: mobileLogin.cookie })).response.status, 401);
    assert.equal((await request('/api/auth/login', { body: { email: customer.email, password: 'old-password' } })).response.status, 401);
    const customerCurrentLogin = await request('/api/auth/login', { body: { email: customer.email, password: 'new-password' } });
    assert.equal(customerCurrentLogin.response.status, 200);
    assert.equal(customer.resetTokenHash, undefined);
    const updatedProfile = await request('/api/auth/me', { method: 'PATCH', cookie: customerCurrentLogin.cookie, body: { fullName: 'Updated Customer', email: customer.email, mobile: customer.mobile, role: 'Admin' } });
    assert.equal(updatedProfile.response.status, 200);
    assert.equal(updatedProfile.data.user.fullName, 'Updated Customer');
    assert.equal(updatedProfile.data.user.role, 'Customer');
    assert.equal(customer.name, 'Updated Customer');
    assert.equal((await request('/api/auth/me', { cookie: customerCurrentLogin.cookie })).data.fullName, 'Updated Customer');
    assert.equal((await request('/api/auth/me', { method: 'PATCH', cookie: customerCurrentLogin.cookie, body: { fullName: 'Updated Customer', email: billingAdmin.email, mobile: customer.mobile } })).response.status, 409);
    assert.equal((await request('/api/auth/me', { method: 'PATCH', cookie: customerCurrentLogin.cookie, body: { fullName: 'X', email: customer.email, mobile: customer.mobile } })).response.status, 400);

    const technician = {
      _id: 'technician', name: 'Test Technician', email: 'tech@example.com', mobile: '+94770000001',
      password: await bcrypt.hash('tech-password', 10), role: 'Technician', isActive: true, sessionVersion: 0,
      async save() { return this; },
    };
    reportTechnician = technician;
    users.push(technician);
    assert.equal((await request('/api/auth/technician/login', { body: { email: customer.email, password: 'new-password' } })).response.status, 403);
    const technicianLogin = await request('/api/auth/technician/login', { body: { email: technician.email, password: 'tech-password' } });
    assert.equal(technicianLogin.response.status, 200);
    assert.equal(technicianLogin.data.role, 'Technician');
    assert.match(technicianLogin.response.headers.get('set-cookie'), /HttpOnly/);
    assert.equal((await request('/api/auth/me', { cookie: technicianLogin.cookie })).data.role, 'Technician');
    billingAdmin.role = 'Finance';
    assert.equal((await request('/api/auth/login', { body: { email: billingAdmin.email, password: 'finance-password' } })).response.status, 403);
    billingAdmin.role = 'Admin';
    const billingLogin = await request('/api/auth/login', { body: { email: billingAdmin.email, password: 'finance-password' } });
    assert.equal(billingLogin.response.status, 200);
    billingAdmin.role = 'Finance';
    assert.equal((await request('/api/admin/billing', { cookie: billingLogin.cookie })).response.status, 401);
    billingAdmin.role = 'Admin';
    const dashboardJobs = [
      { _id: '64f000000000000000000001', serviceNumber: 'JOB-ACTIVE', status: 'In Progress', priority: 'Urgent', customerComplaint: 'Brake noise', updatedAt: new Date(), customer: { name: 'Workshop Customer' }, vehicle: { make: 'Toyota', model: 'Corolla', year: 2022, registrationNumber: 'ABC-1234' }, appointment: { serviceType: 'Brake repair', preferredDate: new Date(), preferredTime: '09:00' } },
      { _id: '64f000000000000000000002', serviceNumber: 'JOB-PENDING', status: 'Inspecting', priority: 'High', updatedAt: new Date(), customer: { name: 'Workshop Customer' }, vehicle: { make: 'Honda', model: 'Civic', registrationNumber: 'XYZ-9876' }, appointment: { serviceType: 'Inspection', preferredDate: new Date(), preferredTime: '10:00' } },
      { _id: '64f000000000000000000003', serviceNumber: 'JOB-READY', status: 'Ready', priority: 'Normal', updatedAt: new Date(), customer: { name: 'Workshop Customer' }, vehicle: { make: 'Suzuki', model: 'Swift' }, appointment: { serviceType: 'Repair', preferredDate: new Date(), preferredTime: '11:00' } },
    ];
    dashboardJobs[2].customer._id = customer._id;
    dashboardJobs[2].customer.email = customer.email;
    dashboardJobs[2].vehicle.registrationNumber = 'ABC-5678';
    dashboardJobs[2].replacedParts = [{ name: 'Oil filter', partNumber: 'OF-1', quantity: 2, unitCost: 125 }];
    dashboardJobs[2].labourEntries = [{ description: 'Service labour', minutes: 60, ratePerHour: 80 }];
    dashboardJobs[2].additionalRepairs = [{ description: 'Approved belt replacement', status: 'Approved', estimatedCost: 20 }, { description: 'Declined repair', status: 'Rejected', estimatedCost: 50 }];
    dashboardJobs[2].timeline = [{ status: 'Ready', timestamp: new Date('2026-10-01T10:00:00.000Z') }];
    dashboardJobs[0].inspection = { findings: '', diagnosis: '', notes: '', issues: [], recommendedRepairs: [] };
    dashboardJobs[0].repairNotes = [];
    dashboardJobs[0].tasks = [];
    dashboardJobs[0].tasks.id = id => dashboardJobs[0].tasks.find(task => String(task._id) === String(id));
    dashboardJobs[0].replacedParts = [];
    dashboardJobs[0].replacedParts.id = id => dashboardJobs[0].replacedParts.find(part => String(part._id) === String(id));
    dashboardJobs[0].replacedParts.pull = id => {
      const index = dashboardJobs[0].replacedParts.findIndex(part => String(part._id) === String(id));
      if (index >= 0) dashboardJobs[0].replacedParts.splice(index, 1);
    };
    dashboardJobs[0].labourEntries = [];
    dashboardJobs[0].additionalRepairs = [];
    dashboardJobs[0].timeline = [];
    dashboardJobs[0].$locals = {};
    dashboardJobs[0].save = async function save() { return this; };
    dashboardJobs[1].additionalRepairs = [];
    dashboardJobs[1].additionalRepairs.id = id => dashboardJobs[1].additionalRepairs.find(repair => String(repair._id) === String(id));
    dashboardJobs[1].tasks = [{ _id: '64f000000000000000000040', title: 'Replace worn belt', status: 'Pending', notes: '' }, { _id: '64f000000000000000000041', title: 'Inspect pulley', status: 'Pending', notes: '' }];
    dashboardJobs[1].tasks.id = id => dashboardJobs[1].tasks.find(task => String(task._id) === String(id));
    dashboardJobs[1].inspection = { findings: '', diagnosis: '', notes: '', issues: [], recommendedRepairs: [] };
    dashboardJobs[1].timeline = [];
    dashboardJobs[1].$locals = {};
    dashboardJobs[1].save = async function save() { return this; };
    t.mock.method(Appointment, 'find', () => ({ sort() { return this; }, populate() { return this; }, lean: async () => [] }));
    t.mock.method(Appointment, 'updateOne', async () => ({ modifiedCount: 1 }));
    t.mock.method(ServiceJob, 'find', query => ({ select() { return this; }, populate() { return this; }, sort() { return this; }, skip() { return this; }, limit() { return this; }, lean: async () => dashboardJobs.filter(job => (!query.status || (query.status.$in ? query.status.$in.includes(job.status) : job.status === query.status)) && (!query.priority || job.priority === query.priority)) }));
    t.mock.method(ServiceJob, 'findOne', query => {
      const found = dashboardJobs.find(job => String(job._id) === String(query._id)) || null;
      const pending = Promise.resolve(found);
      pending.populate = () => pending;
      pending.lean = async () => found;
      return pending;
    });
    t.mock.method(ServiceJob, 'countDocuments', async query => query.timeline ? 1 : query.status?.$in && !query.priority ? dashboardJobs.filter(job => query.status.$in.includes(job.status)).length : query.status === 'Inspecting' ? 1 : query.status === 'In Progress' ? 1 : query.status === 'Waiting for Approval' ? 0 : query.status === 'Ready' ? 1 : query.priority ? 2 : Object.keys(query).length === 1 && query.technician ? dashboardJobs.length : 0);
    t.mock.method(ServiceJob, 'aggregate', async pipeline => pipeline.some(stage => stage.$lookup?.from === 'users') ? [{ _id: technician._id, technicianName: technician.name, jobsCompleted: 2, labourMinutes: 120, revenue: 6500, averageCompletionHours: 6.5 }] : [{ name: 'Brake pad set', partNumber: 'BP-01', unitPrice: 125, lastUsedAt: new Date() }]);
    t.mock.method(Vehicle, 'find', () => ({ select() { return this; }, limit() { return this; }, lean: async () => [] }));
    const dashboardNotifications = [{ _id: 'notice-1', type: 'ServiceJobAssigned', title: 'New job assigned', message: 'JOB-ACTIVE is ready.', link: '/technician/jobs', isRead: false, createdAt: new Date() }];
    t.mock.method(Notification, 'find', () => ({ select() { return this; }, sort() { return this; }, limit() { return this; }, lean: async () => dashboardNotifications }));
    t.mock.method(Notification, 'countDocuments', async () => 1);
    const createdNotifications = [];
    t.mock.method(Notification, 'create', async data => { createdNotifications.push(data); return data; });
    const deliveredNotifications = [];
    t.mock.method(Notification, 'insertMany', async items => { deliveredNotifications.push(...items); return items; });
    const payableInvoice = { _id: '64f000000000000000000063', invoiceNumber: 'INV-OPEN-01', customer: customer._id, paymentStatus: 'Partially Paid', totalAmount: 200, amountPaid: 50 };
    let financeInvoiceRows = [];
    t.mock.method(Invoice, 'findOne', query => {
      const found = String(query._id) === payableInvoice._id ? payableInvoice : financeInvoiceRows.find(invoice => String(invoice._id) === String(query._id)) || null;
      const matchesStatus = !query.paymentStatus?.$in || query.paymentStatus.$in.includes(found?.paymentStatus);
      const pending = Promise.resolve(matchesStatus ? found : null);
      pending.populate = () => pending;
      return pending;
    });
    t.mock.method(Invoice, 'findOneAndUpdate', async (query, update) => { if (String(query._id) !== payableInvoice._id) return null; Object.assign(payableInvoice, update.$set); return payableInvoice; });
    t.mock.method(Invoice, 'updateOne', async () => ({ modifiedCount: 1 }));
    t.mock.method(Invoice, 'create', async data => ({ ...data, _id: '64f000000000000000000060' }));
    financeInvoiceRows = [{ _id: '64f000000000000000000061', invoiceNumber: 'INV-TEST-0001', paymentStatus: 'Draft', totalAmount: 350, amountPaid: 0, parts: [{ name: 'Oil filter', quantity: 2, unitPrice: 125, total: 250 }], labourItems: [{ description: 'Service labour', hours: 1, rate: 80, total: 80 }], partsCost: 250, labourCost: 80, additionalRepairsCost: 20, tax: 0, discount: 0, createdAt: new Date(), customer: { name: 'Workshop Customer', email: customer.email }, serviceJob: { _id: '64f000000000000000000003', serviceNumber: 'JOB-READY', appointment: { serviceType: 'Repair' }, vehicle: { registrationNumber: 'ABC-5678', make: 'Suzuki', model: 'Swift' } } }];
    financeInvoiceRows.push({ _id: payableInvoice._id, invoiceNumber: payableInvoice.invoiceNumber, paymentStatus: payableInvoice.paymentStatus, totalAmount: payableInvoice.totalAmount, amountPaid: payableInvoice.amountPaid, partsCost: 200, labourCost: 0, additionalRepairsCost: 0, customer: { name: 'Test Customer', email: customer.email }, serviceJob: { _id: '64f000000000000000000003', serviceNumber: 'JOB-READY', vehicle: { registrationNumber: 'ABC-5678', make: 'Suzuki', model: 'Swift' } } });
    financeInvoiceRows.push({ _id: '64f000000000000000000064', invoiceNumber: 'INV-OVERDUE-01', paymentStatus: 'Pending', totalAmount: 600, amountPaid: 100, createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000), customer: { _id: customer._id, name: 'Test Customer', email: customer.email }, serviceJob: { _id: '64f000000000000000000003', serviceNumber: 'JOB-READY', vehicle: { registrationNumber: 'ABC-5678', make: 'Suzuki', model: 'Swift' } } });
    t.mock.method(Invoice, 'find', query => ({ sort() { return this; }, limit() { return this; }, populate() { return this; }, lean: async () => query?.paymentStatus ? financeInvoiceRows.filter(invoice => query.paymentStatus.$in.includes(invoice.paymentStatus)) : financeInvoiceRows }));
    const emailInvoice = { _id: '64f000000000000000000062', invoiceNumber: 'INV-ISSUED-01', paymentStatus: 'Pending', totalAmount: 350, amountPaid: 0, customer: { name: 'Workshop Customer', email: customer.email } };
    const sentInvoiceEmails = [];
    t.mock.method(Invoice, 'findById', () => { const pending = Promise.resolve(emailInvoice); pending.populate = () => pending; return pending; });
    t.mock.method(invoiceEmail, 'isConfigured', () => true);
    t.mock.method(invoiceEmail, 'send', async (invoice, recipient) => { sentInvoiceEmails.push({ invoice, recipient }); });
    t.mock.method(invoiceEmail, 'sendReceipt', async (payment, invoice, recipient) => { sentInvoiceEmails.push({ payment, invoice, recipient }); });
    t.mock.method(invoiceEmail, 'sendReminder', async (invoice, recipient, amountDue) => { sentInvoiceEmails.push({ reminderInvoice: invoice, recipient, amountDue }); });
    t.mock.method(Invoice, 'countDocuments', async query => query.paymentStatus === 'Paid' ? 3 : query.paymentStatus === 'Overdue' ? 2 : query.paymentStatus?.$in ? 2 : 7);
    t.mock.method(Invoice, 'aggregate', async pipeline => pipeline.at(-1)?.$group?.averageInvoiceValue ? [{ averageInvoiceValue: 300, invoiceCount: 4 }] : pipeline.some(stage => stage.$unwind === '$parts') ? [{ _id: { name: 'Brake pad set', partNumber: 'BP-01' }, quantity: 4, revenue: 500, cost: 320, invoices: 2 }] : [{ total: 1250 }]);
    const dashboardPayments = [{ _id: 'payment-1', amount: 250, method: 'Bank Transfer', transactionReference: 'BANK-001', receiptNumber: 'RCPT-001', status: 'Completed', createdAt: new Date(), reviewedAt: new Date(), customer: { name: 'Billing Customer' }, invoice: { invoiceNumber: 'INV-001' } }];
    t.mock.method(Payment, 'aggregate', async pipeline => {
      if (pipeline.some(stage => stage.$lookup)) return [{ _id: 'Brake Repairs', revenue: 950, transactions: 3 }, { _id: 'Full Service', revenue: 400, transactions: 1 }];
      const groupId = pipeline[1]?.$group?._id;
      if (groupId?.$dateToString) return [{ _id: groupId.$dateToString.format === '%Y-%m' ? `${new Date().getUTCFullYear()}-${String(new Date().getUTCMonth() + 1).padStart(2, '0')}` : new Date().toISOString().slice(0, 10), total: 400 }];
      if (groupId && typeof groupId === 'object') return [{ _id: { year: new Date().getFullYear(), month: new Date().getMonth() + 1 }, total: 400 }];
      const match = pipeline[0].$match.reviewedAt;
      if (!match.$lt) return [{ total: 400 }];
      const days = (match.$lt - match.$gte) / (24 * 60 * 60 * 1000);
      return [{ total: days < 2 ? 100 : match.$gte.getUTCMonth() === new Date().getUTCMonth() ? 400 : 100 }];
    });
    t.mock.method(Payment, 'countDocuments', async () => dashboardPayments.length);
    t.mock.method(Payment, 'find', () => ({ sort() { return this; }, skip() { return this; }, limit() { return this; }, populate() { return this; }, lean: async () => dashboardPayments }));
    let manualPaymentCount = 0;
    t.mock.method(Payment, 'create', async data => ({ ...data, _id: `64f00000000000000000006${++manualPaymentCount}`, receiptNumber: `RCPT-000000006${manualPaymentCount}`, createdAt: new Date() }));
    t.mock.method(Payment, 'deleteOne', async () => ({ deletedCount: 1 }));
    t.mock.method(JobPhoto, 'find', () => ({ select() { return this; }, sort() { return this; }, lean: async () => [] }));
    t.mock.method(JobPhoto, 'countDocuments', async () => 0);
    t.mock.method(JobPhoto, 'create', async photo => ({ ...photo, _id: '64f000000000000000000010', createdAt: new Date() }));
    const dashboard = await request('/api/auth/technician-dashboard', { cookie: technicianLogin.cookie });
    assert.equal(dashboard.response.status, 200);
    assert.deepEqual(dashboard.data.summary, { assigned: 1, inProgress: 1, waitingForApproval: 0, completedToday: 1, completed: 1, highPriority: 2, today: 2 });
    assert.equal(dashboard.data.activeJob.serviceNumber, 'JOB-ACTIVE');
    assert.equal(dashboard.data.pendingJobs[0].serviceNumber, 'JOB-PENDING');
    assert.equal(dashboard.data.completedJobs[0].serviceNumber, 'JOB-READY');
    assert.equal(dashboard.data.notifications[0].title, 'New job assigned');
    assert.equal((await request('/api/admin/billing', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const financeDashboard = await request('/api/admin/billing', { cookie: billingLogin.cookie });
    assert.equal(financeDashboard.response.status, 200);
    assert.equal(financeDashboard.data.summary.todayRevenue, 100);
    assert.equal(financeDashboard.data.summary.monthlyRevenue, 400);
    assert.equal(financeDashboard.data.summary.totalInvoices, 7);
    assert.equal(financeDashboard.data.summary.outstandingValue, 1250);
    assert.equal(financeDashboard.data.revenueByMonth.length, 6);
    assert.equal(financeDashboard.data.recentPayments[0].invoiceNumber, 'INV-001');
    assert.equal((await request('/api/admin/reports?period=monthly', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const revenueReport = await request('/api/admin/reports?period=monthly', { cookie: billingLogin.cookie });
    assert.equal(revenueReport.response.status, 200);
    assert.equal(revenueReport.data.summary.totalRevenue, 400);
    assert.equal(revenueReport.data.summary.previousRevenue, 100);
    assert.equal(revenueReport.data.summary.averageInvoiceValue, 300);
    assert.equal(revenueReport.data.trend.length, new Date(Date.UTC(new Date().getUTCFullYear(), new Date().getUTCMonth() + 1, 0)).getUTCDate());
    assert.equal(revenueReport.data.trend.find((item) => item.key === new Date().toISOString().slice(0, 10)).revenue, 400);
    assert.equal((await request('/api/admin/reports/by-service', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const serviceReport = await request('/api/admin/reports/by-service?period=monthly', { cookie: billingLogin.cookie });
    assert.equal(serviceReport.response.status, 200);
    assert.equal(serviceReport.data.services.find(item => item.name === 'Brake Repairs').revenue, 950);
    assert.equal(serviceReport.data.highestEarning, 'Brake Repairs');
    assert.equal((await request('/api/admin/reports/parts', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const partsReport = await request('/api/admin/reports/parts?period=monthly', { cookie: billingLogin.cookie });
    assert.equal(partsReport.response.status, 200);
    assert.equal(partsReport.data.summary.quantity, 4);
    assert.equal(partsReport.data.summary.revenue, 500);
    assert.equal(partsReport.data.summary.cost, 320);
    assert.equal(partsReport.data.summary.mostUsedPart, 'Brake pad set');
    assert.equal((await request('/api/admin/reports/technicians', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const technicianReport = await request('/api/admin/reports/technicians?period=monthly', { cookie: billingLogin.cookie });
    assert.equal(technicianReport.response.status, 200);
    assert.equal(technicianReport.data.summary.jobsCompleted, 2);
    assert.equal(technicianReport.data.summary.labourHours, 2);
    assert.equal(technicianReport.data.rows[0].revenue, 6500);
    assert.equal(technicianReport.data.rows[0].averageCompletionHours, 6.5);
    assert.equal((await request('/api/admin/reports?period=custom&from=2026-10-01', { cookie: billingLogin.cookie })).response.status, 400);
    assert.equal((await request('/api/admin/payments/history', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const paymentHistory = await request('/api/admin/payments/history?page=1&limit=25&method=Bank%20Transfer', { cookie: billingLogin.cookie });
    assert.equal(paymentHistory.response.status, 200);
    assert.equal(paymentHistory.data.total, 1);
    assert.equal(paymentHistory.data.payments[0].transactionReference, 'BANK-001');
    assert.equal(paymentHistory.data.payments[0].method, 'Bank Transfer');
    assert.equal(paymentHistory.data.payments[0].customer.name, 'Billing Customer');
    assert.equal((await request('/api/admin/payments/history?from=not-a-date', { cookie: billingLogin.cookie })).response.status, 400);
    assert.equal((await request('/api/admin/payments/payable-invoices', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const payableList = await request('/api/admin/payments/payable-invoices', { cookie: billingLogin.cookie });
    assert.equal(payableList.response.status, 200);
    assert.equal(payableList.data.invoices[0].amountDue, 150);
    const invalidMethod = await request('/api/admin/payments/record', { cookie: billingLogin.cookie, body: { invoiceId: payableInvoice._id, amount: 10, method: 'Cheque' } });
    assert.equal(invalidMethod.response.status, 400);
    const overpayment = await request('/api/admin/payments/record', { cookie: billingLogin.cookie, body: { invoiceId: payableInvoice._id, amount: 151, method: 'Cash' } });
    assert.equal(overpayment.response.status, 400);
    const partialPayment = await request('/api/admin/payments/record', { cookie: billingLogin.cookie, body: { invoiceId: payableInvoice._id, amount: 50, method: 'Cash' } });
    assert.equal(partialPayment.response.status, 201);
    assert.equal(partialPayment.data.invoice.paymentStatus, 'Partially Paid');
    assert.equal(partialPayment.data.invoice.amountDue, 100);
    assert.match(partialPayment.data.payment.receiptNumber, /^RCPT-/);
    assert.match(partialPayment.data.payment.transactionReference, /^CASH-/);
    assert.ok(createdNotifications.some(notification => notification.type === 'PaymentConfirmation' && String(notification.user) === String(customer._id)));
    assert.ok(deliveredNotifications.some(notification => notification.type === 'PaymentConfirmation' && String(notification.user) === 'admin-user'));
    const finalPayment = await request('/api/admin/payments/record', { cookie: billingLogin.cookie, body: { invoiceId: payableInvoice._id, amount: 100, method: 'Card', transactionReference: 'CARD-123' } });
    assert.equal(finalPayment.response.status, 201);
    assert.equal(finalPayment.data.invoice.paymentStatus, 'Paid');
    assert.equal(finalPayment.data.invoice.amountDue, 0);
    assert.equal((await request('/api/admin/payments/outstanding', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const outstanding = await request('/api/admin/payments/outstanding', { cookie: billingLogin.cookie });
    assert.equal(outstanding.response.status, 200);
    assert.equal(outstanding.data.summary.overdueInvoices, 1);
    const overdueInvoice = outstanding.data.invoices.find(invoice => invoice.invoiceNumber === 'INV-OVERDUE-01');
    assert.ok(overdueInvoice.overdueDays >= 29);
    assert.equal(overdueInvoice.amountDue, 500);
    const reminder = await request(`/api/admin/payments/${overdueInvoice.id}/reminder`, { method: 'POST', cookie: billingLogin.cookie });
    assert.equal(reminder.response.status, 200);
    assert.equal(sentInvoiceEmails.at(-1).amountDue, 500);
    assert.equal((await request('/api/admin/invoices/jobs', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const billableJobs = await request('/api/admin/invoices/jobs', { cookie: billingLogin.cookie });
    assert.equal(billableJobs.response.status, 200);
    assert.equal(billableJobs.data.jobs.length, 1);
    assert.equal(billableJobs.data.jobs[0].partsCost, 250);
    assert.equal(billableJobs.data.jobs[0].labourItems[0].hours, 1);
    assert.equal(billableJobs.data.jobs[0].approvedRepairs[0].amount, 20);
    const invalidInvoiceRates = await request('/api/admin/invoices/jobs/64f000000000000000000003/invoice', { cookie: billingLogin.cookie, body: { taxRate: 101 } });
    assert.equal(invalidInvoiceRates.response.status, 400);
    const finalizedInvoice = await request('/api/admin/invoices/jobs/64f000000000000000000003/invoice', { cookie: billingLogin.cookie, body: { taxRate: 5, discountRate: 10, finalize: true } });
    assert.equal(finalizedInvoice.response.status, 200);
    assert.match(finalizedInvoice.data.invoice.invoiceNumber, /^INV-\d+-[A-F0-9]{8}$/);
    assert.equal(finalizedInvoice.data.invoice.paymentStatus, 'Pending');
    assert.equal(finalizedInvoice.data.invoice.partsCost, 250);
    assert.equal(finalizedInvoice.data.invoice.labourCost, 80);
    assert.equal(finalizedInvoice.data.invoice.additionalRepairsCost, 20);
    assert.equal(finalizedInvoice.data.invoice.discount, 35);
    assert.equal(finalizedInvoice.data.invoice.tax, 15.75);
    assert.equal(finalizedInvoice.data.invoice.totalAmount, 330.75);
    assert.equal((await request('/api/admin/invoices', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const financeInvoiceList = await request('/api/admin/invoices', { cookie: billingLogin.cookie });
    assert.equal(financeInvoiceList.response.status, 200);
    assert.equal(financeInvoiceList.data.invoices[0].invoiceNumber, 'INV-TEST-0001');
    assert.equal(financeInvoiceList.data.invoices[0].serviceJob.vehicle.registrationNumber, 'ABC-5678');
    const emailSent = await request('/api/admin/invoices/64f000000000000000000062/send', { method: 'POST', cookie: billingLogin.cookie });
    assert.equal(emailSent.response.status, 200);
    assert.equal(sentInvoiceEmails[0].recipient.email, customer.email);
    assert.equal((await request('/api/admin/invoices/invalid', { method: 'DELETE', cookie: billingLogin.cookie })).response.status, 400);
    assert.equal((await request('/api/admin/invoices/invalid', { method: 'PATCH', cookie: billingLogin.cookie, body: { taxRate: 5 } })).response.status, 400);
    const spareParts = await request('/api/auth/technician/parts?search=brake', { cookie: technicianLogin.cookie });
    assert.equal(spareParts.response.status, 200);
    assert.equal(spareParts.data.parts[0].unitPrice, 125);
    assert.equal((await request('/api/auth/technician/parts?search=brake', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const myJobs = await request('/api/auth/technician/jobs?status=In%20Progress&sort=recent&page=1', { cookie: technicianLogin.cookie });
    assert.equal(myJobs.response.status, 200);
    assert.equal(myJobs.data.total, 2);
    assert.equal(myJobs.data.jobs.length, 2);
    assert.equal(myJobs.data.jobs[0].serviceType, 'Brake repair');
    const history = await request('/api/auth/technician/jobs/history?search=JOB-READY', { cookie: technicianLogin.cookie });
    assert.equal(history.response.status, 200);
    assert.equal(history.data.total, 1);
    assert.equal(history.data.jobs[0].serviceNumber, 'JOB-READY');
    assert.equal(history.data.jobs[0].completedAt, '2026-10-01T10:00:00.000Z');
    assert.equal((await request('/api/auth/technician/jobs/history', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    const jobDetails = await request('/api/auth/technician/jobs/64f000000000000000000001', { cookie: technicianLogin.cookie });
    assert.equal(jobDetails.response.status, 200);
    assert.equal(jobDetails.data.job.priority, 'Urgent');
    assert.equal(jobDetails.data.job.expectedCompletionTime, null);
    assert.equal((await request('/api/auth/technician/jobs/64f000000000000000000099', { cookie: technicianLogin.cookie })).response.status, 404);
    const repairNote = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'repairNote', note: 'Customer notified of inspection results.' } });
    assert.equal(repairNote.response.status, 200);
    assert.equal(dashboardJobs[0].repairNotes[0].note, 'Customer notified of inspection results.');
    const diagnosticUpdate = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'diagnosticReport', result: 'Brake pads below service limit.', issueCategory: 'Brakes', faultDescription: 'Front pads are worn and rotor has scoring.', recommendedAction: 'Replace front brake pads and inspect rotor thickness.', severity: 'High', estimatedRepairHours: 1.5 } });
    assert.equal(diagnosticUpdate.response.status, 200);
    assert.equal(dashboardJobs[0].diagnosticReport.estimatedRepairMinutes, 90);
    const invalidDiagnostic = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'diagnosticReport', result: 'Test', issueCategory: 'Invalid', faultDescription: 'Fault', recommendedAction: 'Repair', severity: 'High', estimatedRepairHours: 1 } });
    assert.equal(invalidDiagnostic.response.status, 400);
    const photoUpload = await request('/api/auth/technician/jobs/64f000000000000000000001/photos', { cookie: technicianLogin.cookie, body: { filename: 'brake.png', contentType: 'image/png', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bWsAAAAASUVORK5CYII=' } });
    assert.equal(photoUpload.response.status, 201);
    assert.equal(photoUpload.data.photo.filename, 'brake.png');
    const inspectionBeforeStart = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'inspection', findings: 'Finding', diagnosis: 'Diagnosis' } });
    assert.equal(inspectionBeforeStart.response.status, 409);
    const repairBeforeInspection = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'status', status: 'In Progress' } });
    assert.equal(repairBeforeInspection.response.status, 409);
    const inspectionStart = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'inspectionStart' } });
    assert.equal(inspectionStart.response.status, 200);
    const inspectionUpdate = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'inspection', findings: 'Belt cracking', diagnosis: 'Belt replacement recommended', issues: ['Drive belt crack'], recommendedRepairs: ['Replace drive belt'], notes: 'Checked under inspection lamp.' } });
    assert.equal(inspectionUpdate.response.status, 200);
    const inspectionImage = await request('/api/auth/technician/jobs/64f000000000000000000002/photos', { cookie: technicianLogin.cookie, body: { filename: 'belt.png', contentType: 'image/png', category: 'Inspection', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bWsAAAAASUVORK5CYII=' } });
    assert.equal(inspectionImage.response.status, 201);
    assert.equal(inspectionImage.data.photo.category, 'Inspection');
    const repairEvidence = await request('/api/auth/technician/jobs/64f000000000000000000001/photos', { cookie: technicianLogin.cookie, body: { filename: 'damaged-belt.png', contentType: 'image/png', category: 'RepairEvidence', evidenceType: 'Damaged Part', description: 'Cracks across the belt ribs.', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/bWsAAAAASUVORK5CYII=' } });
    assert.equal(repairEvidence.response.status, 201);
    assert.equal(repairEvidence.data.photo.evidenceType, 'Damaged Part');
    assert.equal(repairEvidence.data.photo.description, 'Cracks across the belt ribs.');
    const inspectionComplete = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'inspection', findings: 'Belt cracking', diagnosis: 'Belt replacement recommended', issues: ['Drive belt crack'], recommendedRepairs: ['Replace drive belt'], notes: 'Checked under inspection lamp.', complete: true } });
    assert.equal(inspectionComplete.response.status, 200);
    assert.ok(dashboardJobs[1].inspection.completedAt);
    assert.equal(dashboardJobs[1].timeline.at(-1).status, 'Inspection Completed');
    const startRepairs = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'status', status: 'In Progress', notes: 'Inspection is complete; we are beginning the approved repair.' } });
    assert.equal(startRepairs.response.status, 200);
    const taskAdd = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'taskAdd', title: 'Replace front pads' } });
    assert.equal(taskAdd.response.status, 200);
    dashboardJobs[0].tasks[0]._id = '64f000000000000000000020';
    const taskUpdate = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'taskUpdate', taskId: '64f000000000000000000020', title: 'Replace front brake pads', notes: 'Used OEM replacement pads.', status: 'Complete' } });
    assert.equal(taskUpdate.response.status, 200);
    assert.equal(dashboardJobs[0].tasks[0].title, 'Replace front brake pads');
    assert.equal(dashboardJobs[0].tasks[0].notes, 'Used OEM replacement pads.');
    assert.ok(dashboardJobs[0].tasks[0].completedAt);
    const partAdd = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'partAdd', name: 'Brake pad set', partNumber: 'BP-01', quantity: 1, unitCost: 125 } });
    assert.equal(partAdd.response.status, 200);
    assert.equal(dashboardJobs[0].replacedParts[0].unitCost, 125);
    dashboardJobs[0].replacedParts[0]._id = '64f000000000000000000030';
    const partRemove = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'partRemove', partId: '64f000000000000000000030' } });
    assert.equal(partRemove.response.status, 200);
    assert.equal(dashboardJobs[0].replacedParts.length, 0);
    const labourAdd = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'labourAdd', description: 'Brake service', labourType: 'Repair', hours: 1.5, ratePerHour: 80 } });
    assert.equal(labourAdd.response.status, 200);
    assert.equal(dashboardJobs[0].labourEntries[0].minutes, 90);
    assert.equal(dashboardJobs[0].labourEntries[0].ratePerHour, 80);
    const timerStart = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'labourTimerStart', description: 'Brake test', labourType: 'Testing', ratePerHour: 60 } });
    assert.equal(timerStart.response.status, 200);
    assert.ok(dashboardJobs[0].activeLabourTimer.startedAt);
    const secondTimerStart = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'labourTimerStart', description: 'Duplicate', labourType: 'Repair', ratePerHour: 60 } });
    assert.equal(secondTimerStart.response.status, 409);
    dashboardJobs[0].activeLabourTimer.startedAt = new Date(Date.now() - 5 * 60000);
    const timerStop = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'labourTimerStop' } });
    assert.equal(timerStop.response.status, 200);
    assert.equal(dashboardJobs[0].labourEntries[1].labourType, 'Testing');
    assert.ok(dashboardJobs[0].labourEntries[1].minutes >= 5 && dashboardJobs[0].labourEntries[1].minutes <= 6);
    assert.equal(dashboardJobs[0].activeLabourTimer, undefined);
    const approvalRequest = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'approvalRequest', description: 'Replace worn belt', explanation: 'Cracking found during inspection.', relatedTaskId: '64f000000000000000000040', parts: [{ name: 'Drive belt', quantity: 2, unitCost: 90 }], labourCost: 60 } });
    assert.equal(approvalRequest.response.status, 200);
    assert.equal(dashboardJobs[1].status, 'Waiting for Approval');
    assert.equal(dashboardJobs[1].additionalRepairs[0].estimatedCost, 240);
    assert.equal(dashboardJobs[1].additionalRepairs[0].parts[0].totalCost, 180);
    dashboardJobs[1].additionalRepairs[0]._id = '64f000000000000000000050';
    const pendingApprovalList = await request('/api/repair-approvals', { cookie: customerCurrentLogin.cookie });
    assert.equal(pendingApprovalList.response.status, 200);
    assert.ok(pendingApprovalList.data.some(repair => repair.status === 'Pending' && repair.estimatedCost === 240));
    const rejectedDecision = await request('/api/repair-approvals/64f000000000000000000002/repairs/64f000000000000000000050/decision', { method: 'PATCH', cookie: customerCurrentLogin.cookie, body: { decision: 'Rejected', comment: 'Please do not replace this yet.' } });
    assert.equal(rejectedDecision.response.status, 200);
    assert.equal(dashboardJobs[1].tasks[0].status, 'Cancelled');
    assert.equal(dashboardJobs[1].additionalRepairs[0].customerComment, 'Please do not replace this yet.');
    assert.equal(dashboardJobs[1].status, 'In Progress');
    assert.match(dashboardJobs[1].timeline.at(-1).notes, /Please do not replace this yet/);
    const secondApproval = await request('/api/auth/technician/jobs/64f000000000000000000002/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'approvalRequest', description: 'Inspect pulley', explanation: 'Pulley bearing has play.', relatedTaskId: '64f000000000000000000041', parts: [], labourCost: 20 } });
    assert.equal(secondApproval.response.status, 200);
    dashboardJobs[1].additionalRepairs[1]._id = '64f000000000000000000051';
    const approvedDecision = await request('/api/repair-approvals/64f000000000000000000002/repairs/64f000000000000000000051/decision', { method: 'PATCH', cookie: customerCurrentLogin.cookie, body: { decision: 'Approved', comment: 'Approved, please proceed.' } });
    assert.equal(approvedDecision.response.status, 200);
    assert.equal(dashboardJobs[1].status, 'In Progress');
    assert.equal(dashboardJobs[1].timeline.at(-1).status, 'Additional repair approved');
    const technicianApprovalView = await request('/api/auth/technician/jobs/64f000000000000000000002', { cookie: technicianLogin.cookie });
    assert.equal(technicianApprovalView.response.status, 200);
    assert.equal(technicianApprovalView.data.job.additionalRepairs[0].status, 'Rejected');
    assert.equal(technicianApprovalView.data.job.additionalRepairs[0].customerComment, 'Please do not replace this yet.');
    assert.equal(technicianApprovalView.data.job.additionalRepairs[1].status, 'Approved');
    const statusUpdate = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'status', status: 'Final Test', notes: 'Repair tasks are complete; final safety checks are underway.' } });
    assert.equal(statusUpdate.response.status, 200);
    assert.equal(dashboardJobs[0].status, 'Final Test');
    assert.equal(dashboardJobs[0].timeline.at(-1).notes, 'Repair tasks are complete; final safety checks are underway.');
    const earlyReady = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'status', status: 'Ready', notes: 'Attempting to mark this ready before testing.' } });
    assert.equal(earlyReady.response.status, 409);
    const finalTestStart = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'finalTestStart' } });
    assert.equal(finalTestStart.response.status, 200);
    const incompleteFinalTest = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'finalTestComplete', checklist: [] } });
    assert.equal(incompleteFinalTest.response.status, 400);
    const finalTestItems = ['Brakes', 'Steering', 'Lights and signals', 'Tyres and wheels', 'Fluid leaks', 'Road test'];
    const failedFinalTest = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'finalTestComplete', checklist: finalTestItems.map(item => ({ item, result: item === 'Brakes' ? 'Failed' : 'Passed' })), notes: 'Brake pedal travel exceeds specification.', unresolvedIssue: 'Brake pedal still feels soft.' } });
    assert.equal(failedFinalTest.response.status, 200);
    assert.equal(dashboardJobs[0].finalTest.result, 'Failed');
    assert.equal(dashboardJobs[0].status, 'In Progress');
    const restartFinalTest = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'status', status: 'Final Test', notes: 'Brake system adjusted; beginning final checks again.' } });
    assert.equal(restartFinalTest.response.status, 200);
    assert.equal((await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'finalTestStart' } })).response.status, 200);
    const passedFinalTest = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'finalTestComplete', checklist: finalTestItems.map(item => ({ item, result: 'Passed' })), notes: 'All checks passed on the second test.' } });
    assert.equal(passedFinalTest.response.status, 200);
    assert.equal(dashboardJobs[0].finalTest.result, 'Passed');
    const readyUpdate = await request('/api/auth/technician/jobs/64f000000000000000000001/card', { method: 'PATCH', cookie: technicianLogin.cookie, body: { action: 'completeJob', tasksVerified: true, partsVerified: true, labourVerified: true, reportNotes: 'Brake service completed and final test passed.' } });
    assert.equal(readyUpdate.response.status, 200);
    assert.equal(dashboardJobs[0].status, 'Ready');
    assert.equal(dashboardJobs[0].billingInvoice, '64f000000000000000000060');
    assert.equal(dashboardJobs[0].finalReport.notes, 'Brake service completed and final test passed.');
    assert.equal(readyUpdate.data.invoice.paymentStatus, 'Draft');
    assert.ok(readyUpdate.data.invoice.totalAmount >= 125 && readyUpdate.data.invoice.totalAmount <= 126);
    assert.ok(deliveredNotifications.some(notification => notification.type === 'ServiceJobCompleted'));
    assert.equal((await request('/api/auth/technician-dashboard', { cookie: customerCurrentLogin.cookie })).response.status, 403);
    assert.equal((await request('/api/auth/technician/change-password', {
      cookie: technicianLogin.cookie, body: { currentPassword: 'incorrect', newPassword: 'better-tech-password', confirmPassword: 'better-tech-password' },
    })).response.status, 400);
    assert.equal((await request('/api/auth/technician/change-password', {
      cookie: technicianLogin.cookie, body: { currentPassword: 'tech-password', newPassword: 'short', confirmPassword: 'short' },
    })).response.status, 400);
    const changed = await request('/api/auth/technician/change-password', {
      cookie: technicianLogin.cookie,
      body: { currentPassword: 'tech-password', newPassword: 'better-tech-password', confirmPassword: 'better-tech-password' },
    });
    assert.equal(changed.response.status, 200);
    assert.match(changed.response.headers.get('set-cookie'), /Expires=Thu, 01 Jan 1970/);
    assert.equal(technician.sessionVersion, 1);
    assert.equal(sessions.some(session => session.user === technician._id), false);
    assert.equal((await request('/api/auth/me', { cookie: technicianLogin.cookie })).response.status, 401);
    assert.equal((await request('/api/auth/technician/login', { body: { email: technician.email, password: 'tech-password' } })).response.status, 401);
    assert.equal((await request('/api/auth/technician/login', { body: { email: technician.email, password: 'better-tech-password' } })).response.status, 200);

    passwordResetEmail.isConfigured = () => false;
    assert.equal((await request('/api/auth/forgot-password', { body: { email: customer.email } })).response.status, 503);
    assert.equal((await request('/api/auth/forgot-password', { body: { email: 'unknown@example.com' } })).response.status, 503);
    for (let i = 0; i < 5; i++) await request('/api/auth/forgot-password', { body: { email: 'unknown@example.com' } });
    assert.equal((await request('/api/auth/forgot-password', { body: { email: 'unknown@example.com' } })).response.status, 429);
  } finally {
    server.closeAllConnections();
    await new Promise(resolve => server.close(resolve));
  }
});
